import { PrismaClient } from '@prisma/client';

export async function seedSetores(prisma: PrismaClient) {
  console.log('🔹 Criando Setores...');
  await prisma.setor.createMany({
    data: [
      { nome: 'Agregadores de dados' },
      { nome: 'Água, Saneamento e Energia' },
      { nome: 'Aluguel de Carros' },
      { nome: 'Associação' },
      { nome: 'Bancos, Financeiras e Administradoras de Cartão' },
      { nome: 'Birôs de Crédito' },
      { nome: 'Condomínios' },
      { nome: 'Conselho Profissional' },
      { nome: 'Corretoras, Distribuidoras de Títulos e Investimentos' },
      { nome: 'Defensoria Pública' },
      { nome: 'Desenvolvimento de Sistemas' },
      { nome: 'Educação' },
      { nome: 'Empresas de Pagamento Eletrônico' },
      { nome: 'Empresas de Recuperação de Crédito' },
      { nome: 'Entretenimento' },
      { nome: 'Farmacêutico' },
      { nome: 'Hotéis' },
      { nome: 'Imobiliário e Construção Civil' },
      { nome: 'Indústria' },
      { nome: 'Jornalismo' },
      { nome: 'Ministério Público' },
      { nome: 'N/A' },
      { nome: 'Partido Político' },
      { nome: 'Plataforma Digital - Intermediador' },
      { nome: 'Plataforma Digital - Comércio Eletrônico' },
      { nome: 'Plataforma Digital - Rede Social' },
      { nome: 'Poder Executivo' },
      { nome: 'Poder Judiciário' },
      { nome: 'Poder Legislativo' },
      { nome: 'Religioso' },
      { nome: 'Saúde' },
      { nome: 'Seguros' },
      { nome: 'Serventia Extrajudicial' },
      { nome: 'Serviços' },
      { nome: 'Sindicato' },
      { nome: 'Tecnologia' },
      { nome: 'Telecomunicações' },
      { nome: 'Terceiro Setor' },
      { nome: 'Transporte Aéreo' },
      { nome: 'Transporte Terrestre: ônibus' },
      { nome: 'Varejo' },
    ],
    skipDuplicates: true,
  });
}
